global:
  scrape_interval: 1s

scrape_configs:
  - job_name: consumer
    static_configs:
      - targets: ["benchmarks-consumer.getconvoy.io"]

remote_write:
  - url: https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push
    basic_auth:
      username: 350276
      password: glc_eyJvIjoiNjEwODMxIiwibiI6InN0YWNrLTMyNTAzMi1obS1iZW5jaG1hcmstY29uc3VtZXItc2VydmVyIiwiayI6IjI1MTY3cm1TMTJyWXJPc201M3hFU3U5ayIsIm0iOnsiciI6InVzIn19